name: Generate .NET Component Diagram

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Install NDepend (evaluation version)
      run: |
        wget https://www.ndepend.com/ndownload/NDependTrial.zip
        unzip NDependTrial.zip -d ./ndepend
        chmod +x ./ndepend/NDepend.Console.exe

    - name: Generate Code Analysis and Diagram
      run: |
        dotnet build
        ./ndepend/NDepend.Console.exe analysis -i ./ndepend/NDependProject.ndproj -o analysis_result
        mv analysis_result/GraphDir/GraphClass.svg diagram.svg

    - name: Upload Diagram
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-diagram
        path: diagram.svg
